name: colonyapp310
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.2=pyhc872135_1
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - altair==5.5.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - importlib-metadata==6.11.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - narwhals==2.11.0
      - numpy==1.26.4
      - packaging==23.2
      - pandas==2.2.3
      - pillow==9.5.0
      - protobuf==4.25.8
      - pulearn==0.0.11
      - pyarrow==22.0.0
      - pydeck==0.9.1
      - pygments==2.19.2
      - pympler==1.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pytz-deprecation-shim==0.1.0.post0
      - referencing==0.37.0
      - requests==2.32.5
      - rich==13.9.4
      - rpds-py==0.28.0
      - scikit-learn==1.5.2
      - scipy==1.15.3
      - six==1.16.0
      - smmap==5.0.2
      - streamlit==1.25.0
      - streamlit-image-coordinates==0.1.6
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tornado==6.5.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - tzlocal==4.3.1
      - urllib3==2.5.0
      - validators==0.35.0
      - zipp==3.23.0
prefix: /Users/ekello73/miniconda3/envs/colonyapp310
